# -*- coding: utf-8 -*-
"""Train and test creation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wFbLhnmmsLBB5VKsvbZ76M5XrfBBNVBy
"""

#CSV File Processing
import csv
import glob
from pathlib import Path
import os
#Data Processing
import pandas as pd #Data Processing

from google.colab import drive
drive.mount('/content/drive')

# setting work directory 
wd = 'drive/Shared drives/UptakeDS/Data'
os.chdir(wd)

# Making test files

path = 'Data 2014-2016/'    # use your path

count = 0 

for y in [2014]:
  for j in range(7,13):
    
    if len(str(j-3)) == 1:
      i = '0'+str(j-3)
    else:
      i = str(j-3)
      
    file = "Copy of "+str(y)+"-"+i+"-*.csv"
    all_files = glob.glob(os.path.join(path, file))
    
    df_from_each_file = (pd.read_csv(f) for f in all_files)
    concatenated_df   = pd.concat(df_from_each_file, ignore_index=True)

    concatenated_df[:].to_csv('test_'+str(count)+'.csv')
    
    count = count +1

# Making train files

path = 'Data 2014-2016/'    # use your path

count = 0 

for y in [2014]:
  for j in range(7,13):
    a = []
    for k in range(1,7):

      if len(str(j-k)) == 1:
        b = '0'+str(j-k)
      else:
        b = str(j-k)

      a.append(b)
    print(a)

    frames =[]
    for l in range(len(a)):
      file = "Copy of "+str(y)+"-"+a[l]+"-*.csv"
      read1 = glob.glob(os.path.join(path, file))
      df_from_each_file = (pd.read_csv(f) for f in read1)
      concatenated_df   = pd.concat(df_from_each_file, ignore_index=True)

      frames.append(concatenated_df)

    result = pd.concat(frames)

    result[:].to_csv('train_'+str(count)+'.csv')

    count = count +1